import club from "../assets/club.svg";
import diamond from "../assets/diamond.svg";
import heart from "../assets/heart.svg";
import spade from "../assets/spade.svg";

const cardEditors = {
  AC: { suit: `${club}`, cardNumber: "A", value: 1 | 11, quantity: 1 },
  AD: { suit: `${diamond}`, cardNumber: "A", value: 1 | 11, quantity: 1 },
  AH: { suit: `${heart}`, cardNumber: "A", value: 1 | 11, quantity: 1 },
  AS: { suit: `${spade}`, cardNumber: "A", value: 1 | 11, quantity: 1 },
  "2C": { suit: `${club}`, cardNumber: "2", value: 2, quantity: 1 },
  "2D": { suit: `${diamond}`, cardNumber: "2", value: 2, quantity: 1 },
  "2H": { suit: `${heart}`, cardNumber: "2", value: 2, quantity: 1 },
  "2S": { suit: `${spade}`, cardNumber: "2", value: 2, quantity: 1 },
  "3C": { suit: `${club}`, cardNumber: "3", value: 3, quantity: 1 },
  "3D": { suit: `${diamond}`, cardNumber: "3", value: 3, quantity: 1 },
  "3H": { suit: `${heart}`, cardNumber: "3", value: 3, quantity: 1 },
  "3S": { suit: `${spade}`, cardNumber: "3", value: 3, quantity: 1 },
  "4C": { suit: `${club}`, cardNumber: "4", value: 4, quantity: 1 },
  "4D": { suit: `${diamond}`, cardNumber: "4", value: 4, quantity: 1 },
  "4H": { suit: `${heart}`, cardNumber: "4", value: 4, quantity: 1 },
  "4S": { suit: `${spade}`, cardNumber: "4", value: 4, quantity: 1 },
  "5C": { suit: `${club}`, cardNumber: "5", value: 5, quantity: 1 },
  "5D": { suit: `${diamond}`, cardNumber: "5", value: 5, quantity: 1 },
  "5H": { suit: `${heart}`, cardNumber: "5", value: 5, quantity: 1 },
  "5S": { suit: `${spade}`, cardNumber: "5", value: 5, quantity: 1 },
  "6C": { suit: `${club}`, cardNumber: "6", value: 6, quantity: 1 },
  "6D": { suit: `${diamond}`, cardNumber: "6", value: 6, quantity: 1 },
  "6H": { suit: `${heart}`, cardNumber: "6", value: 6, quantity: 1 },
  "6S": { suit: `${spade}`, cardNumber: "6", value: 6, quantity: 1 },
  "7C": { suit: `${club}`, cardNumber: "7", value: 7, quantity: 1 },
  "7D": { suit: `${diamond}`, cardNumber: "7", value: 7, quantity: 1 },
  "7H": { suit: `${heart}`, cardNumber: "7", value: 7, quantity: 1 },
  "7S": { suit: `${spade}`, cardNumber: "7", value: 7, quantity: 1 },
  "8C": { suit: `${club}`, cardNumber: "8", value: 8, quantity: 1 },
  "8D": { suit: `${diamond}`, cardNumber: "8", value: 8, quantity: 1 },
  "8H": { suit: `${heart}`, cardNumber: "8", value: 8, quantity: 1 },
  "8S": { suit: `${spade}`, cardNumber: "8", value: 8, quantity: 1 },
  "9C": { suit: `${club}`, cardNumber: "9", value: 9, quantity: 1 },
  "9D": { suit: `${diamond}`, cardNumber: "9", value: 9, quantity: 1 },
  "9H": { suit: `${heart}`, cardNumber: "9", value: 9, quantity: 1 },
  "9S": { suit: `${spade}`, cardNumber: "9", value: 9, quantity: 1 },
  "0C": { suit: `${club}`, cardNumber: "10", value: 10, quantity: 1 },
  "0D": { suit: `${diamond}`, cardNumber: "10", value: 10, quantity: 1 },
  "0H": { suit: `${heart}`, cardNumber: "10", value: 10, quantity: 1 },
  "0S": { suit: `${spade}`, cardNumber: "10", value: 10, quantity: 1 },
  JC: { suit: `${club}`, cardNumber: "J", value: 10, quantity: 1 },
  JD: { suit: `${diamond}`, cardNumber: "J", value: 10, quantity: 1 },
  JH: { suit: `${heart}`, cardNumber: "J", value: 10, quantity: 1 },
  JS: { suit: `${spade}`, cardNumber: "J", value: 10, quantity: 1 },
  QC: { suit: `${club}`, cardNumber: "Q", value: 10, quantity: 1 },
  QD: { suit: `${diamond}`, cardNumber: "Q", value: 10, quantity: 1 },
  QH: { suit: `${heart}`, cardNumber: "Q", value: 10, quantity: 1 },
  QS: { suit: `${spade}`, cardNumber: "Q", value: 10, quantity: 1 },
  KC: { suit: `${club}`, cardNumber: "K", value: 10, quantity: 1 },
  KD: { suit: `${diamond}`, cardNumber: "K", value: 10, quantity: 1 },
  KH: { suit: `${heart}`, cardNumber: "K", value: 10, quantity: 1 },
  KS: { suit: `${spade}`, cardNumber: "K", value: 10, quantity: 1 },
};

export default cardEditors;
